version: '3'

services:
  frontend:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=super-app
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mysql:8.0.28
    environment:
      - MYSQL_DATABASE=super-app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80

volumes:
  db-data:
